version: '3'

services:
  api-dev:
    build: .
    container_name: api-dev
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dater
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    restart: always
    volumes:
      - ./db_dater:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./src:/frontend/src
    ports:
      - '3000:3000'