# Generated by Django 5.0 on 2023-12-27 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Someone', max_length=30)),
                ('telegram_id', models.CharField(max_length=9, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expiration_date', models.DateField(default=datetime.date(2023, 12, 29))),
            ],
        ),
    ]
