# Generated by Django 5.0.2 on 2024-02-19 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 2, 21)),
        ),
    ]
