# Generated by Django 5.0.2 on 2024-02-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_alter_invitation_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 2, 22)),
        ),
    ]
