# Generated by Django 5.0.2 on 2024-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_invitation_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
