# Generated by Django 5.0.2 on 2024-02-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_alter_invitation_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='telegram_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
